### PR TITLE
Reproductible use case for Spring WebFlux and ServerResponse possible issue

### PR DESCRIPTION
**Pull request by jhaeyaert**
# Reproductible problem with Spring 5 RC2 WebFlux and ServerResponse

## Problem description

Using WebFlux in reactive way, I was expecting this king of thing will work but I always get a 406 status ('Not Acceptable').

```java
	@GetMapping(path = "/bug", produces = "text/html; charset=utf-8")
	@ResponseBody
	public Mono<ServerResponse> getTest() {

		return ServerResponse.ok().body(Mono.just("<html><body><p>This should work</p></body></html>"), String.class);
	}
```
The use of ServerResponse is a way to have a better control on http status and content response in case of error or empty  observable (ex : 404 if ```Mono.empty()``` is returned)

After a deep search I found that the AbstractMessageWriterResultHandler (~ line 112) never find appropriate HttpMessageWriter able to write element of ```ServerResponse``` type.

Is it a bug or do I miss something ?

## How to reproduce

 1. Clone the projet 
```
git clone https://github.com/jhaeyaert/spring-framework-issues.git
cd ./spring-framework-issues/SPR-15677
```

 2. Compile the project using maven
```
mvn clean package
```
 3. Run the project

```
java -jar target/SPR-15677-0.0.1-SNAPSHOT.jar
```

 4. Test the reproductible case

```
curl -D- http://localhost:8181/bug
```
You will get a 406 status code 'Not Acceptable'

```
HTTP/1.1 406 Not Acceptable
content-length: 0
```

### CODE REVIEW

**Comment by snicoll** [comment]
@jhaeyaert thanks for the PR but I am not following the link with SPR-15673. Can you explain?

**Comment by jhaeyaert** [comment]
Do you mean the command ```cd ./spring-framework-issues/SPR-15673``` is not working ?

I don't know well how github works and how to directly checkout a PR ? I suppose you have to clone my forked repository then go to the SPR-15673 folder ?

```
git clone https://github.com/jhaeyaert/spring-framework-issues.git
cd ./spring-framework-issues/SPR-15673
```

Let me know if it's OK for you ?

Thanks

**Comment by snicoll** [comment]
Sorry no. I mean how is [SPR-15673](https://jira.spring.io/browse/SPR-15673) related to your repro project? Perhaps you've made a typo and it's a different Jira issue number?

**Comment by jhaeyaert** [comment]
OK my bad, this is the first time I post an issue on Spring Framework... I missed the part related to  JIRA Issue tracker on the README.

The issue is now referenced here : https://jira.spring.io/browse/SPR-15677

```
git clone https://github.com/jhaeyaert/spring-framework-issues.git
cd ./spring-framework-issues/SPR-15677
```

Sorry for the loss of time. I will be more efficient next time ;-)

**Comment by jhaeyaert** [comment]
@rstoyanchev explains me that ServerResponse was not designed for use in annotated controllers (see https://jira.spring.io/browse/SPR-15677). 

If someone encounters the same problem as me, here is an example working with annotated controller. The example is a POST that take data body and return html content in reactive way :

```java
	@PostMapping(path = "/test", produces = "text/html; charset=utf-8")
	@ResponseBody
	public Mono<ResponseEntity<String>> getTest(@RequestBody Mono<String> data) {

		return data.map(s -> "<html><body><p>" + s + "</p></body></html>").flatMap(s -> Mono.just(ResponseEntity.ok(s)));
	}
```

I close the pull request.

**Pull request closed without merging**
