### PR TITLE
Add repro project for SPR-15855

### PR DESCRIPTION
**Pull request by sl-wxx**
A dependency with type "ParentService<ParentGeneric>", 
	but only candidate with type ChildService<ChildGeneric> is supplied. 
	I think this should work, (a generic covariance type should be accepted), but spring refused it.

### CODE REVIEW

**Comment by snicoll** [comment]
@sl-wxx the test is passing for me. Can you please update the PR to make it fail?

**Comment by sl-wxx** [comment]
I'm very sorry. I don't know how to make it fail. Can you please give me some help. (I really tried a lot)

**Comment by snicoll** [comment]
The whole purpose of this sample is for you to show us what you think is an issue. If the test is not failing, how can I demonstrate the issue using this sample?

**Comment by sl-wxx** [comment]
I have realized this is not an issue. It's my mistake. But I don't know how to close it. Can you give me some help? Or may you close it directly?

**Pull request closed without merging**
